site_name: Squiller
site_url: https://docs.ruuda.nl/squiller
repo_url: https://github.com/ruuda/squiller
strict: true

# Directory urls do not interact well with trailing slashes. Instead, render
# them with .html here, and then in the minimizer we strip that. (And the
# webserver config allows both.)
use_directory_urls: false

theme:
  name: null
  custom_dir: docs/theme

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
      permalink_title: null

nav:
  - Overview: index.md
  - User guide:
    - Usage: usage.md
    - Annotating queries: annotating-queries.md
    - Data types: datatypes.md
    - Targets: targets.md
    - Changelog: changelog.md
  - Development:
    - Building: building.md
    - Golden tests: golden-tests.md
