site_name: Querybinder
repo_url: https://github.com/ruuda/querybinder
strict: true
theme:
  name: null
  custom_dir: docs/theme
nav:
  - Overview: index.md
  - User guide:
    - Usage: usage.md
    - Annotating queries: annotating-queries.md
    - Data types: datatypes.md
  - Development:
    - Building: building.md
    - Golden tests: golden-tests.md
